name: Build and Push Docker Image

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    name: Build and Push Docker Image

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3       

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current datetime for tag
        id: date
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      
      - name: Get repository owner name for tag and convert to lowercase
        id: owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64  # [NOTE] Can't use matrix to run parallel builds: the later job will overwrite the latest tag
          tags: |
            ghcr.io/${{ steps.owner.outputs.owner }}/gradio-torrent-tool:${{ steps.date.outputs.datetime }}
            ghcr.io/${{ steps.owner.outputs.owner }}/gradio-torrent-tool:latest
          # Ditch unknown/unknown tag in GitHub Packages
          provenance: false
          sbom: false
          